# Generated by Django 4.2.16 on 2024-10-23 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('prod_period', models.IntegerField()),
                ('replace_period', models.TextField()),
                ('docs', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('logo_file_path', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='InstallDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DELETED', 'Deleted'), ('FORMED', 'Formed'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('new_client_surname', models.TextField(blank=True, null=True)),
                ('replace_reason', models.TextField(blank=True, null=True)),
                ('issue_organization', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                  'db_table': 'install_document_requests',
            },
        ),
        migrations.CreateModel(
            name='DocumentInRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacing_documents.document')),
                ('replacing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='replacing_documents.installdocumentrequest')),
            ],
            options={
                'db_table': 'document_in_request',
                'unique_together': {('replacing_request', 'document')},
            },
        ),
    ]
