# Generated by Django 4.2.16 on 2024-11-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replacing_documents', '0003_remove_installdocumentrequest_issue_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_active',
        ),
    ]
