# Generated by Django 4.2.16 on 2024-12-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacing_documents', '0004_remove_document_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentinrequest',
            name='issue_organization',
        ),
        migrations.AddField(
            model_name='document',
            name='number_length',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentinrequest',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='documentinrequest',
            name='new_document_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='logo_file_path',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
