# Generated by Django 4.2.16 on 2024-12-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacing_documents', '0005_remove_documentinrequest_issue_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentinrequest',
            name='new_document_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
