# Generated by Django 4.2.17 on 2024-12-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('replacing_documents', '0006_alter_document_number_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='installdocumentrequest',
            name='new_client_surname',
            field=models.TextField(blank=True, default='Пятигорская'),
        ),
        migrations.AlterField(
            model_name='installdocumentrequest',
            name='replace_reason',
            field=models.TextField(blank=True, default='Вступление в брак'),
        ),
    ]
